/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.House;
import model.DataService;

/**
 *
 * @author harshinichandrika
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    public UpdateJPanel() {
    }

    
    DataService history;
    
    public UpdateJPanel(DataService history) {
        initComponents();
        this.history=history;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public boolean isHouse(String s) {  
    return s != null && s.matches("^[a-zA-Z][a-zA-Z\\s-]+[a-zA-Z]$");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHouses = new javax.swing.JTable();
        lblHouseName = new javax.swing.JLabel();
        lblHouseId = new javax.swing.JLabel();
        lblCommunityId = new javax.swing.JLabel();
        txtHouseName = new javax.swing.JTextField();
        txtHouseId = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        txtCommunityId = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Update");

        tblHouses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "House Name", "House Id", "Community Id"
            }
        ));
        jScrollPane1.setViewportView(tblHouses);

        lblHouseName.setText("House Name:");

        lblHouseId.setText("Community Id:");

        lblCommunityId.setText("House Id:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHouseId)
                            .addComponent(lblCommunityId)
                            .addComponent(lblHouseName))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHouseName, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txtHouseId)
                            .addComponent(txtCommunityId, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addGap(128, 128, 128))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView)
                .addGap(49, 49, 49)
                .addComponent(btnUpdate)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouseName)
                    .addComponent(txtHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunityId)
                    .addComponent(txtHouseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouseId)
                    .addComponent(txtCommunityId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnView))
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void tblHousesClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:'
         int selectedRowIndex = tblHouses.getSelectedRow();
            if(selectedRowIndex<0){
                JOptionPane.showMessageDialog(this, "Please select a profile to Update");
                return;
            }
            DefaultTableModel model= (DefaultTableModel) tblHouses.getModel();
            House selectedHouse = (House) model.getValueAt(selectedRowIndex, 0);
            txtHouseName.setText(selectedHouse.getHouseName());
            txtHouseId.setText(selectedHouse.getHouselId());
            txtCommunityId.setText(selectedHouse.getCommunityId());
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tblHouses.getModel();
        if(tblHouses.getSelectedRowCount() == 1){

            String houseName=txtHouseName.getText();
            if(!isHouse(txtHouseName.getText())) {
            
            JOptionPane.showMessageDialog(this, "Please enter a valid House name.");
            return;

        }
        if(houseName.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "House Name is empty.");
            return;

        }
            String houselId=txtHouseId.getText();
            if(houselId.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "City ID is empty.");
            return;
        }
            
            String communityId=txtCommunityId.getText();
            
            int selectedRowIndex = tblHouses.getSelectedRow();

            House hs = history.getHistory().get(selectedRowIndex);

            hs.setHouseName(houseName);
            hs.setHouselId(houselId);
            hs.setCommunityId(communityId);
            
            //update message
            JOptionPane.showMessageDialog(this, "The record has been updated successfully");
            populateTable();

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex=tblHouses.getSelectedRow();
        
        if(selectedRowIndex<0)
        {
           JOptionPane.showMessageDialog(this,"Please select a valid entry");
           return;
        }
        
        DefaultTableModel model =(DefaultTableModel) tblHouses.getModel();
        House selectedHouse = (House) model.getValueAt(selectedRowIndex, 0);
        
        txtHouseName.setText(selectedHouse.getHouseName());
        txtHouseId.setText(selectedHouse.getHouselId());
        txtCommunityId.setText(selectedHouse.getCommunityId());
    }//GEN-LAST:event_btnViewActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCommunityId;
    private javax.swing.JLabel lblHouseId;
    private javax.swing.JLabel lblHouseName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblHouses;
    private javax.swing.JTextField txtCommunityId;
    private javax.swing.JTextField txtHouseId;
    private javax.swing.JTextField txtHouseName;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

DefaultTableModel model = (DefaultTableModel) tblHouses.getModel();
    model.setRowCount(0);
    for(House hs : history.getHistory()){
        Object[] row = new Object[10];
        row[0] = hs;
        row[1] = hs.getHouselId();
        row[2] = hs.getCommunityId();
        model.addRow(row);
    }
    }

}
